image: node:latest

before_script:
#  - export PIP_CACHE_DIR="pip-cache"
  - "npm install"

stages:
    - compile
    - package
    - deploy

cache:
    key: "$CI_PROJECT_NAME\\$CI_BUILD_REF_NAME"
    paths:
        - dist/
        - node_modules
        - public.tar.gz

compile_job:
    stage: compile
    script:
        - "pwd;ls"
        - "npm install typescript@'>=2.1.0 <2.4.0'"
        - "npm rebuild node-sass"
        - "npm run build"

package_job:
    stage: package
    only:
        - release
        - master
        #test ci
        - develop
    script:
        - "pwd;ls"
        - "tar czf public.tar.gz dist/"
        - ls


deploy_release_job:
    stage: deploy
    only:
        - release
        # test ci
        - develop
    script:
        - "./script/deploy-release.sh"

deploy_production_job:
    stage: deploy
    only:
        - master
    script:
        - "./script/deploy-production.sh"
