import { Component, AfterViewChecked } from '@angular/core';
import { CookieService } from 'ngx-cookie-service';

interface TechnologySingle {
    title: string;
    sub: string;
    desc: string;
    name: string;
    icon: string;
}

interface Technology {
    mainTitle: string;
    mainSub: string;
    pages: TechnologySingle[];
}

@Component({
    selector: 'app-tech',
    templateUrl: './tech.component.html',
    styleUrls: ['./tech.component.scss']
})

export class TechComponent implements AfterViewChecked {
    language = 'zh';
    langIndex = 0;
    nowIndex = 0;

    nowTech: Technology;
    nowTechSingle: TechnologySingle;
    technologies: Technology[] = [
        {
            mainTitle: '核心技术优势',
            mainSub: '我们完全自主研发的语义识别人工智能引擎可以实现多轮人机对话及上下文理解，采用独特的偏重实例层的多层语义知识网络，支持基于图模板映射的规则归纳和知识推理。',
            pages: [
                {
                    title: '获得精准数据',
                    sub: '齐悟能知道某个用户具体的信息，而且可以联系起来精准定位。',
                    desc: '打个比方，他在乐逗玩了什么游戏，玩的怎么样了，打到多少关了，充了多少钱，这个虽然腾讯能知道，但是百度阿里巴巴肯定是不知道的。然后也能知道他患了什么病，现在健康状况是什么样的，比如百度可能知道他去了哪家医院，搜了什么病，但是具体病情肯定是不知道的，然后腾讯之类也肯定收集不到。这就是我们比BAT数据上的优势。而且百度只知道他搜了什么，而我们是用户亲口告诉具体情况，我们也能理解用户在相关业务里所有的数据。',
                    name: '精准数据',
                    icon: '/assets/img/tech_icons/tech_icon1_w.png'
                },
                {
                    title: '支持复杂逻辑和业务',
                    sub: '齐悟拥有革命性的语音交互技术，涵盖了语音识别、语义识别和语音合成一整套语音交互技术。',
                    desc: '现在知名度比较高的几个机器人都是闲聊为主，顶多增加一些调闹钟、查天气的关键词查询式的助理功能。齐悟可以根据企业用户需求定制业务逻辑，处理更加复杂的业务，如买机票、订酒店、点外卖，通过一系列多轮对话搜集用户意图或直接一次性理解多句复杂句子表的达，这是传统一问一答聊天机器人做不到的。并且支持多个话题跳转，网状逻辑，而不是传统客服的线性菜单式逻辑。',
                    name: '复杂逻辑',
                    icon: '/assets/img/tech_icons/tech_icon2_w.png'
                },
                {
                    title: '敏捷开发',
                    sub: '齐悟运用革命性智能算法提高百倍以上的开发效率，快速迭代，试试更新。',
                    desc: '国内大多数智能客服公司做一个demo需要花4个月时间，我们只需要3天就可以做出效果更好的demo，一周即可做出成品，能够快速测试投产，并且动态根据客户需求调整。在产品的开发及迭代快速的泛娱乐领域，齐悟智能客服有很强的竞争力。',
                    name: '敏捷开发',
                    icon: '/assets/img/tech_icons/tech_icon3_w.png'
                },
                {
                    title: '深度定制化',
                    sub: '人工智能巨头的技术有各自的先进性，但是极少会针对中小企业提供深度定制服务。',
                    desc: '互联网巨头不会给中小企业定制专门的产品，我们可以给不同行业定制，目前轻松覆盖游戏、客服、虚拟偶像、智能硬件、教育、医疗、语音助手等领域，帮助各类规模企业解决实际问题，降低企业成本，提高营收水平及品牌价值。',
                    name: '定制化',
                    icon: '/assets/img/tech_icons/tech_icon4_w.png'
                },
                {
                    title: '自主研发核心引擎',
                    sub: '齐悟机器人在记忆、推理等功能完胜国内外一线竞争对手。',
                    desc: '齐悟的引擎已经开发了10多年，可以轻松实现快速定制，更重要的是开发费用相比竞争对手更低，而且迭代速度快，版本更新灵活，具有绝对的竞争优势。齐悟技术的核心是采用独特的偏重实例层的多层语义知识网络，基于图模板映射的规则归纳和知识推理，从而实现多轮人机对话及上下文语义理解。',
                    name: '自主研发',
                    icon: '/assets/img/tech_icons/tech_icon5_w.png'
                },
                {
                    title: '甲方压力小',
                    sub: '运用标准化的流程，减少人工成本，大大加快模型训练时间。',
                    desc: '传统的智能客服是通过机器学习的方式进行训练，会产生两个问题：需要甲方提供大量语料数据进行训练，许多企业往往无法提供数据；同时每一次定制都需要甲方出人力进行大量的人工标记，费时劳力。可以说，他们是人工堆积出来的智能，而不是真正的人工智能。齐悟只需客户提供给人类客服学习的《培训手册》或标准的业务流程图，齐悟就能建立自己的逻辑、快速学习处理业务，实现接近真人的自然交互。后续需要增删知识，只需要在神经网络中增加或减少节点即可完成需求。',
                    name: '成本优势',
                    icon: '/assets/img/tech_icons/tech_icon6_w.png'
                }
            ]
        },
        {
            mainTitle: 'CORE TECHNOLOGIES',
            mainSub: 'Our self-developed speech-recognition artificial intelligence can achieve smooth conversation and context comprehension through the unique advantage generated by the combination of weighted multi-layer knowledge web and induction / deduction logic with projection modeling process.',
            pages: [
                {
                    title: 'Accurate Data',
                    sub: 'We can pinpoint user information with related data analyzed by Chewrobot.',
                    desc: 'For instance, a person is playing an online game. All the related game status information such as progress, item purchased, gaming efficiency, can all be obtained to assess and predict the person’s future choices. Most gaming company have those information but lack of means to process. Similar, the person could reach symptoms or certain remedies online. The search engine can have those vague pieces of information, but we are able to gather more specific details because our user will key in those personally. Further more, we can comprehend those data and gives a more specific feedbacks for users.',
                    name: 'Accurate Data',
                    icon: '/assets/img/tech_icons/tech_icon1_w.png'
                },
                {
                    title: 'Complex Business Logic',
                    sub: 'Chewrobot have revolutionized voice interactive technology though integration of voice recognition, semantic interpretation and speech synthesis.',
                    desc: 'Currently all well known interactive robot, Siri, Alexa, XiaoIce, are all random chat majored with a little functional services provided. We can provide fully customizable resolution to our client, with the ability to process unique business logic, such as travel booking, order delivery and shopping all through conversation.',
                    name: 'Complex Logic',
                    icon: '/assets/img/tech_icons/tech_icon2_w.png'
                },
                {
                    title: 'Agile Development',
                    sub: 'Chewrobot utilize innovative smart algorithm improve more than hundred times than traditional means. Faster development, realtime update.',
                    desc: 'Most smart service company needs more than 4 month to create an demo for their customer, where we only needs less than a week to present a more compelling result. we can deploy our service quicker and more suitable by the needs of the customer.',
                    name: 'Agile Development',
                    icon: '/assets/img/tech_icons/tech_icon3_w.png'
                },
                {
                    title: 'Fully Customizable',
                    sub: 'Chewrobot can be fully customized according to different demands.',
                    desc: 'Google, Amazon and Apple have developed their AI system suitable for their own enterprise rather for any other companies. We can provide customizable AI for small business across all field. ',
                    name: 'Customization',
                    icon: '/assets/img/tech_icons/tech_icon4_w.png'
                },
                {
                    title: 'Self-developed Engine',
                    sub: 'Chewrobot is superior than most competitors in deduction and memorization function.',
                    desc: 'Chewrobot engine has been developed for more than 10 years. With frequent update and high focus on logic deduction, we have built competitive advantage. The core technology of the engine utilize weighted multi-layer knowledge web and induction/deduction logic with projection modeling process.',
                    name: 'Engine',
                    icon: '/assets/img/tech_icons/tech_icon5_w.png'
                },
                {
                    title: 'More for Client',
                    sub: 'Standarized process, less training cost, faster into production.',
                    desc: 'Contrast to the traditional AI training methods which needs large amount of data with manually marked, Chewrobot requires only business logic which actual human use to handle cases. This not only greatly decrease the cost of time and money, also make Chewrobot forming its own learning logic path. The entire process is easy to alter in order to increase or remove service.',
                    name: 'Price',
                    icon: '/assets/img/tech_icons/tech_icon6_w.png'
                }
            ]
        }
    ]

    constructor(private cookieService: CookieService) {
        this.language = this.cookieService.get('lang');
        if (this.language === 'en') {
            this.langIndex = 1;
        } else {
            this.langIndex = 0;
        }
        this.nowTech = this.technologies[this.langIndex];
        this.nowTechSingle = this.nowTech.pages[this.nowIndex];
    }

    ngAfterViewChecked() {
        $('.tech-menu-inner').hover(function () {
            $(this).children('img').addClass('animated bounce');
            $(this).children('p').addClass('animated bounce');
        }, function () {
            $(this).children('img').removeClass('animated bounce');
            $(this).children('p').removeClass('animated bounce');
        });
    }

    changeTech(index: number) {
        this.nowTechSingle = this.nowTech.pages[index];
        this.nowIndex = index;
    }
}
